"""create queries table

Revision ID: 0004_create_queries_table
Revises: 0003_add_timescale_hypertable
Create Date: 2024-05-21 12:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid

# revision identifiers, used by Alembic.
revision = '0004_create_queries_table'
down_revision = '0003_add_timescale_hypertable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('queries',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('query_text', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('mqf_score', sa.Float(), nullable=True),
        sa.Column('is_flagged', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    
    op.add_column('leads', sa.Column('query_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_leads_query_id', 'leads', 'queries', ['query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_constraint('fk_leads_query_id', 'leads', type_='foreignkey')
    op.drop_column('leads', 'query_id')
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ### 