"""add simhash to leads

Revision ID: 0005_add_simhash_to_leads
Revises: 0004_create_queries_table
Create Date: 2024-05-21 13:00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005_add_simhash_to_leads'
down_revision = '0004_create_queries_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('simhash', sa.BIGINT(), nullable=True))
    op.add_column('leads', sa.Column('is_potential_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_leads_simhash'), 'leads', ['simhash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_simhash'), table_name='leads')
    op.drop_column('leads', 'is_potential_duplicate')
    op.drop_column('leads', 'simhash')
    # ### end Alembic commands ### 