# Provider cost configuration for Lead Sorcerer
# All costs are in USD per unit

openrouter:
  unit: '1k_tokens'
  usd_per_unit: 0.0020

gse:
  unit: 'request'
  usd_per_unit: 0.0005

firecrawl:
  unit: 'extract'
  usd_per_unit: 0.0010
