apiVersion: v1
kind: ConfigMap
metadata:
  name: leadpoet-config
  namespace: leadpoet-prod
data:
  # Database Configuration
  DB_HOST: "leadpoet-prod.${DB_ENDPOINT}"
  DB_PORT: "5432"
  DB_NAME: "leadpoet"
  
  # Redis Configuration
  REDIS_HOST: "${REDIS_ENDPOINT}"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_BROKERS}"
  KAFKA_TOPIC_MINER_SNIPPETS: "miner.snippets"
  KAFKA_TOPIC_OUTCOME_EVENTS: "outcome.events"
  
  # Application Configuration
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  
  # Scoring Configuration
  BM25_THRESHOLD: "8"
  TIME_DECAY_TAU: "90"
  MAX_LEADS_PER_QUERY: "2000"
  MIN_LEADS_PER_QUERY: "200"
  
  # LLM Configuration
  LLM_MAX_TOKENS: "8"
  LLM_TEMPERATURE: "0.2"
  LLM_MAX_CALL_RATIO: "0.3"
  
  # Performance Configuration
  LATENCY_P95_THRESHOLD: "400"
  LATENCY_P99_THRESHOLD: "550"
  COST_AVG_THRESHOLD: "0.002"
  COST_P99_THRESHOLD: "0.004" 