apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leadpoet-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "leadpoet-api.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "leadpoet-api.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "leadpoet-api.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "leadpoet-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.deployment.containerSecurityContext | nindent 12 }}
          env:
            # Database configuration
            - name: DB_HOST
              value: {{ printf "%s.%s" .Values.infrastructure.database.prefix .Values.infrastructure.database.endpoint | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DB_PASSWORD
            
            # Redis configuration
            - name: REDIS_HOST
              value: {{ .Values.infrastructure.redis.endpoint | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: REDIS_DB
              value: {{ .Values.env.REDIS_DB | quote }}
            
            # Application configuration
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            
            # Performance configuration
            - name: LATENCY_P95_THRESHOLD
              value: {{ .Values.env.LATENCY_P95_THRESHOLD | quote }}
            - name: LATENCY_P99_THRESHOLD
              value: {{ .Values.env.LATENCY_P99_THRESHOLD | quote }}
            - name: COST_AVG_THRESHOLD
              value: {{ .Values.env.COST_AVG_THRESHOLD | quote }}
            - name: COST_P99_THRESHOLD
              value: {{ .Values.env.COST_P99_THRESHOLD | quote }}
            
            # Scoring configuration
            - name: BM25_THRESHOLD
              value: {{ .Values.env.BM25_THRESHOLD | quote }}
            - name: TIME_DECAY_TAU
              value: {{ .Values.env.TIME_DECAY_TAU | quote }}
            - name: MAX_LEADS_PER_QUERY
              value: {{ .Values.env.MAX_LEADS_PER_QUERY | quote }}
            - name: MIN_LEADS_PER_QUERY
              value: {{ .Values.env.MIN_LEADS_PER_QUERY | quote }}
            
            # LLM configuration
            - name: LLM_MAX_TOKENS
              value: {{ .Values.env.LLM_MAX_TOKENS | quote }}
            - name: LLM_TEMPERATURE
              value: {{ .Values.env.LLM_TEMPERATURE | quote }}
            - name: LLM_MAX_CALL_RATIO
              value: {{ .Values.env.LLM_MAX_CALL_RATIO | quote }}
            
            # API Keys (from secrets)
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: OPENAI_API_KEY
            - name: PDL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: PDL_API_KEY
            - name: CLEARBIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: CLEARBIT_API_KEY
            
            # Datadog APM configuration
            - name: DD_ENV
              value: {{ .Values.global.environment | quote }}
            - name: DD_SERVICE
              value: "leadpoet-intent-model"
            - name: DD_VERSION
              value: {{ .Chart.AppVersion | quote }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126" 