{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "leadpoet-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "leadpoet-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "leadpoet-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.namespaceLabels.ingress.name }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: 8000
    # Allow traffic from monitoring (Prometheus, etc.)
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.namespaceLabels.monitoring.name }}
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: 8000
    # Allow traffic from within the same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 8000
    {{- with .Values.networkPolicy.ingressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS traffic for external APIs
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow database connections
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.namespaceLabels.database.name }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow Redis connections
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.namespaceLabels.redis.name }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow Datadog agent communication
    - to:
        - podSelector:
            matchLabels:
              app: datadog-agent
      ports:
        - protocol: TCP
          port: 8126
    {{- with .Values.networkPolicy.egressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }} 