"""Canonical constraints for the V2 validator hotkey authority.

This module is deliberately dependency-free and Python 3.7 compatible.  It
does not hold or use key material.  The validator enclave uses it to prove
that a requested sr25519 signature belongs to one of two closed domains:

* an explicitly recognized LeadPoet/Bittensor application message; or
* the exact SCALE payload for ``commit_timelocked_mechanism_weights`` whose
  encrypted commitment was generated by the enclave for an authoritative
  V2 weight receipt.

The host is never allowed to submit arbitrary bytes to a generic signing
oracle.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

from leadpoet_canonical.attested_v2 import canonical_json, sha256_bytes, sha256_json


CHAIN_SIGNING_PROFILE_SCHEMA_VERSION = "leadpoet.chain_signing_profile.v2"
WEIGHT_EXTRINSIC_AUTHORIZATION_SCHEMA_VERSION = (
    "leadpoet.weight_extrinsic_authorization.v2"
)
SERVE_AXON_EXTRINSIC_AUTHORIZATION_SCHEMA_VERSION = (
    "leadpoet.serve_axon_extrinsic_authorization.v2"
)
APPLICATION_SIGNATURE_SCHEMA_VERSION = "leadpoet.application_signature.v2"
WEIGHT_INPUT_REQUEST_SCHEMA_VERSION = "leadpoet.weight_inputs_request.v2"
WEIGHT_INPUT_REQUEST_PREFIX = "LEADPOET_WEIGHT_INPUTS_V2|"

_HASH_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
_RAW_HASH_RE = re.compile(r"^[0-9a-f]{64}$")
_HEX_RE = re.compile(r"^[0-9a-f]*$")
_HOTKEY_RE = re.compile(r"^[1-9A-HJ-NP-Za-km-z]{40,64}$")
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
_TIMESTAMP_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$"
)

_PROFILE_FIELDS = {
    "schema_version",
    "network",
    "chain_endpoint",
    "genesis_hash",
    "spec_version",
    "transaction_version",
    "version_key",
    "commit_call_index",
    "serve_axon_call_index",
    "commit_reveal_version",
    "mechid",
    "tempo",
    "subnet_reveal_period_epochs",
    "block_time_millis",
    "max_snapshot_block_drift",
    "extrinsic_period",
    "signed_extensions",
}

_EXPECTED_SIGNED_EXTENSIONS = (
    "CheckMortality",
    "CheckNonce",
    "ChargeTransactionPayment",
    "CheckMetadataHash",
    "CheckSpecVersion",
    "CheckTxVersion",
    "CheckGenesis",
    "CheckMortalityAdditionalSigned",
    "CheckMetadataHashAdditionalSigned",
)


class HotkeyAuthorityV2Error(ValueError):
    """A hotkey request is not in an explicitly authorized V2 domain."""


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise HotkeyAuthorityV2Error(message)


def _integer(value: Any, field: str, *, minimum: int = 0, maximum: int) -> int:
    _require(
        isinstance(value, int) and not isinstance(value, bool),
        "%s must be an integer" % field,
    )
    _require(minimum <= value <= maximum, "%s is outside its range" % field)
    return int(value)


def _raw_hash(value: Any, field: str) -> str:
    normalized = str(value or "").strip().lower()
    _require(bool(_RAW_HASH_RE.fullmatch(normalized)), "%s is invalid" % field)
    return normalized


def _hash(value: Any, field: str) -> str:
    normalized = str(value or "").strip().lower()
    _require(bool(_HASH_RE.fullmatch(normalized)), "%s is invalid" % field)
    return normalized


def _hex_bytes(value: Any, field: str, *, exact_bytes: Optional[int] = None) -> bytes:
    normalized = str(value or "").strip().lower()
    _require(
        len(normalized) % 2 == 0 and bool(_HEX_RE.fullmatch(normalized)),
        "%s is invalid hex" % field,
    )
    result = bytes.fromhex(normalized)
    if exact_bytes is not None:
        _require(len(result) == exact_bytes, "%s has the wrong length" % field)
    return result


def _timestamp(value: Any, field: str) -> Tuple[str, datetime]:
    normalized = str(value or "")
    _require(bool(_TIMESTAMP_RE.fullmatch(normalized)), "%s is invalid" % field)
    try:
        parsed = datetime.fromisoformat(normalized.replace("Z", "+00:00"))
    except ValueError as exc:
        raise HotkeyAuthorityV2Error("%s is invalid" % field) from exc
    _require(parsed.tzinfo is not None, "%s must include a timezone" % field)
    return normalized, parsed.astimezone(timezone.utc)


def compact_scale_uint(value: int) -> bytes:
    """Encode a non-negative integer using Substrate SCALE compact encoding."""

    normalized = _integer(value, "compact integer", maximum=(1 << 536) - 1)
    if normalized < 1 << 6:
        return bytes((normalized << 2,))
    if normalized < 1 << 14:
        return ((normalized << 2) | 0x01).to_bytes(2, "little")
    if normalized < 1 << 30:
        return ((normalized << 2) | 0x02).to_bytes(4, "little")
    length = max(4, (normalized.bit_length() + 7) // 8)
    _require(length <= 67, "compact integer is too large")
    return bytes((((length - 4) << 2) | 0x03,)) + normalized.to_bytes(
        length, "little"
    )


def encode_mortal_era(*, period: int, current: int) -> bytes:
    """Match Substrate's two-byte mortal-era encoding."""

    normalized_period = _integer(period, "era period", minimum=4, maximum=65536)
    _require(
        normalized_period & (normalized_period - 1) == 0,
        "era period must be a power of two",
    )
    normalized_current = _integer(current, "era current", maximum=(1 << 64) - 1)
    phase = normalized_current % normalized_period
    quantize_factor = max(normalized_period >> 12, 1)
    quantized_phase = (phase // quantize_factor) * quantize_factor
    trailing_zeros = normalized_period.bit_length() - 1
    encoded = min(15, max(1, trailing_zeros - 1)) | (
        (quantized_phase // quantize_factor) << 4
    )
    return int(encoded).to_bytes(2, "little")


def mortal_era_bounds(*, period: int, current: int) -> Tuple[int, int]:
    """Return the inclusive birth and exclusive death blocks for a mortal era."""

    normalized_period = _integer(period, "era period", minimum=4, maximum=65536)
    _require(
        normalized_period & (normalized_period - 1) == 0,
        "era period must be a power of two",
    )
    normalized_current = _integer(current, "era current", maximum=(1 << 64) - 1)
    phase = normalized_current % normalized_period
    quantize_factor = max(normalized_period >> 12, 1)
    quantized_phase = (phase // quantize_factor) * quantize_factor
    birth = normalized_current - (
        (normalized_current - quantized_phase) % normalized_period
    )
    return birth, birth + normalized_period


def validate_chain_signing_profile(value: Mapping[str, Any]) -> Dict[str, Any]:
    _require(
        isinstance(value, Mapping) and set(value) == _PROFILE_FIELDS,
        "chain signing profile fields are invalid",
    )
    _require(
        value.get("schema_version") == CHAIN_SIGNING_PROFILE_SCHEMA_VERSION,
        "chain signing profile schema is invalid",
    )
    network = str(value.get("network") or "")
    endpoint = str(value.get("chain_endpoint") or "")
    _require(bool(re.fullmatch(r"[a-z][a-z0-9_-]{1,31}", network)), "network is invalid")
    _require(endpoint.startswith("wss://") and len(endpoint) <= 512, "chain endpoint is invalid")
    genesis_hash = _raw_hash(value.get("genesis_hash"), "genesis_hash")
    call_index = _hex_bytes(value.get("commit_call_index"), "commit_call_index", exact_bytes=2)
    serve_axon_call_index = _hex_bytes(
        value.get("serve_axon_call_index"),
        "serve_axon_call_index",
        exact_bytes=2,
    )
    signed_extensions = value.get("signed_extensions")
    _require(
        isinstance(signed_extensions, list)
        and tuple(signed_extensions) == _EXPECTED_SIGNED_EXTENSIONS,
        "signed extension profile differs from the measured SDK contract",
    )
    return {
        "schema_version": CHAIN_SIGNING_PROFILE_SCHEMA_VERSION,
        "network": network,
        "chain_endpoint": endpoint,
        "genesis_hash": genesis_hash,
        "spec_version": _integer(
            value.get("spec_version"), "spec_version", maximum=(1 << 32) - 1
        ),
        "transaction_version": _integer(
            value.get("transaction_version"),
            "transaction_version",
            maximum=(1 << 32) - 1,
        ),
        "version_key": _integer(
            value.get("version_key"), "version_key", maximum=(1 << 64) - 1
        ),
        "commit_call_index": call_index.hex(),
        "serve_axon_call_index": serve_axon_call_index.hex(),
        "commit_reveal_version": _integer(
            value.get("commit_reveal_version"),
            "commit_reveal_version",
            maximum=(1 << 16) - 1,
        ),
        "mechid": _integer(value.get("mechid"), "mechid", maximum=(1 << 8) - 1),
        "tempo": _integer(
            value.get("tempo"), "tempo", minimum=1, maximum=(1 << 32) - 1
        ),
        "subnet_reveal_period_epochs": _integer(
            value.get("subnet_reveal_period_epochs"),
            "subnet_reveal_period_epochs",
            minimum=1,
            maximum=(1 << 16) - 1,
        ),
        "block_time_millis": _integer(
            value.get("block_time_millis"),
            "block_time_millis",
            minimum=1,
            maximum=120000,
        ),
        "max_snapshot_block_drift": _integer(
            value.get("max_snapshot_block_drift"),
            "max_snapshot_block_drift",
            minimum=1,
            maximum=1024,
        ),
        "extrinsic_period": _integer(
            value.get("extrinsic_period"),
            "extrinsic_period",
            minimum=4,
            maximum=65536,
        ),
        "signed_extensions": list(_EXPECTED_SIGNED_EXTENSIONS),
    }


def chain_signing_profile_hash(value: Mapping[str, Any]) -> str:
    return sha256_json(validate_chain_signing_profile(value))


def encode_commit_timelocked_call(
    *,
    profile: Mapping[str, Any],
    netuid: int,
    commitment: bytes,
    reveal_round: int,
) -> bytes:
    normalized = validate_chain_signing_profile(profile)
    commitment_bytes = bytes(commitment)
    _require(0 < len(commitment_bytes) <= 1 << 20, "commitment size is invalid")
    return b"".join(
        (
            bytes.fromhex(normalized["commit_call_index"]),
            _integer(netuid, "netuid", maximum=(1 << 16) - 1).to_bytes(2, "little"),
            normalized["mechid"].to_bytes(1, "little"),
            compact_scale_uint(len(commitment_bytes)),
            commitment_bytes,
            _integer(
                reveal_round, "reveal_round", maximum=(1 << 64) - 1
            ).to_bytes(8, "little"),
            normalized["commit_reveal_version"].to_bytes(2, "little"),
        )
    )


def encode_weight_signature_payload(
    *,
    profile: Mapping[str, Any],
    call_bytes: bytes,
    era_current: int,
    nonce: int,
    block_hash: str,
) -> Tuple[bytes, bytes]:
    """Return the SCALE preimage and the exact bytes sr25519 must sign.

    ``substrate-interface`` hashes an extrinsic payload with BLAKE2b-256 when
    it exceeds 256 bytes.  Timelocked commitments normally take that path.
    """

    normalized = validate_chain_signing_profile(profile)
    call = bytes(call_bytes)
    _require(2 <= len(call) <= (1 << 20) + 32, "call bytes are outside limit")
    block_hash_bytes = _hex_bytes(block_hash, "block_hash", exact_bytes=32)
    preimage = b"".join(
        (
            call,
            encode_mortal_era(
                period=normalized["extrinsic_period"], current=era_current
            ),
            compact_scale_uint(_integer(nonce, "nonce", maximum=(1 << 64) - 1)),
            compact_scale_uint(0),  # ChargeTransactionPayment tip is fixed to zero.
            b"\x00",  # CheckMetadataHash mode = Disabled.
            normalized["spec_version"].to_bytes(4, "little"),
            normalized["transaction_version"].to_bytes(4, "little"),
            bytes.fromhex(normalized["genesis_hash"]),
            block_hash_bytes,
            b"\x00",  # CheckMetadataHash additional value = None.
        )
    )
    signed = (
        hashlib.blake2b(preimage, digest_size=32).digest()
        if len(preimage) > 256
        else preimage
    )
    return preimage, signed


def encode_signed_extrinsic_v2(
    *,
    hotkey_public_key_hex: str,
    signature_hex: str,
    era_period: int,
    era_current: int,
    nonce: int,
    call_data_hex: str,
) -> bytes:
    """Encode the exact signed Substrate V4 extrinsic emitted by the SDK.

    The production signing profile fixes zero tip and disabled metadata-hash
    mode.  Reconstructing the complete bytes inside Nitro lets the enclave
    later prove that this exact extrinsic appeared in a finalized block.
    """

    public_key = _hex_bytes(
        hotkey_public_key_hex, "hotkey_public_key", exact_bytes=32
    )
    signature = _hex_bytes(signature_hex, "signature", exact_bytes=64)
    call_data = _hex_bytes(call_data_hex, "call_data")
    _require(2 <= len(call_data) <= (1 << 20) + 32, "call data is outside limit")
    body = b"".join(
        (
            b"\x84",  # signed extrinsic, format version 4
            b"\x00",  # MultiAddress::Id
            public_key,
            b"\x01",  # MultiSignature::Sr25519
            signature,
            encode_mortal_era(period=era_period, current=era_current),
            compact_scale_uint(_integer(nonce, "nonce", maximum=(1 << 64) - 1)),
            compact_scale_uint(0),  # ChargeTransactionPayment tip
            b"\x00",  # CheckMetadataHash mode = Disabled
            call_data,
        )
    )
    return compact_scale_uint(len(body)) + body


def signed_extrinsic_hash_v2(extrinsic: bytes) -> str:
    raw = bytes(extrinsic)
    _require(bool(raw), "signed extrinsic is empty")
    return "0x" + hashlib.blake2b(raw, digest_size=32).hexdigest()


def build_weight_extrinsic_authorization_v2(
    *,
    profile: Mapping[str, Any],
    validator_hotkey: str,
    hotkey_public_key_hex: str,
    epoch_id: int,
    netuid: int,
    weight_receipt_hash: str,
    weight_submission_event_hash: str,
    weights_hash: str,
    sparse_uids: Sequence[int],
    sparse_weights_u16: Sequence[int],
    commitment: bytes,
    reveal_round: int,
    era_current: int,
    nonce: int,
    block_hash: str,
) -> Dict[str, Any]:
    normalized_profile = validate_chain_signing_profile(profile)
    hotkey = str(validator_hotkey or "")
    _require(bool(_HOTKEY_RE.fullmatch(hotkey)), "validator_hotkey is invalid")
    hotkey_public_key = _hex_bytes(
        hotkey_public_key_hex, "hotkey_public_key", exact_bytes=32
    )
    uids = [
        _integer(uid, "uid", maximum=(1 << 16) - 1) for uid in sparse_uids
    ]
    values = [
        _integer(weight, "weight", minimum=1, maximum=(1 << 16) - 1)
        for weight in sparse_weights_u16
    ]
    _require(uids and len(uids) == len(values), "sparse weight vector is invalid")
    _require(uids == sorted(uids) and len(set(uids)) == len(uids), "UIDs are not canonical")
    call = encode_commit_timelocked_call(
        profile=normalized_profile,
        netuid=netuid,
        commitment=commitment,
        reveal_round=reveal_round,
    )
    preimage, signed = encode_weight_signature_payload(
        profile=normalized_profile,
        call_bytes=call,
        era_current=era_current,
        nonce=nonce,
        block_hash=block_hash,
    )
    body = {
        "schema_version": WEIGHT_EXTRINSIC_AUTHORIZATION_SCHEMA_VERSION,
        "validator_hotkey": hotkey,
        "hotkey_public_key": hotkey_public_key.hex(),
        "epoch_id": _integer(epoch_id, "epoch_id", maximum=(1 << 64) - 1),
        "netuid": _integer(netuid, "netuid", maximum=(1 << 16) - 1),
        "weight_receipt_hash": _hash(
            weight_receipt_hash, "weight_receipt_hash"
        ),
        "weight_submission_event_hash": _hash(
            weight_submission_event_hash, "weight_submission_event_hash"
        ),
        "weights_hash": _raw_hash(weights_hash, "weights_hash"),
        "sparse_uids": uids,
        "sparse_weights_u16": values,
        "chain_signing_profile_hash": sha256_json(normalized_profile),
        "commitment_hex": bytes(commitment).hex(),
        "commitment_hash": sha256_bytes(bytes(commitment)),
        "reveal_round": _integer(
            reveal_round, "reveal_round", maximum=(1 << 64) - 1
        ),
        "call_data_hex": call.hex(),
        "call_data_hash": sha256_bytes(call),
        "era_current": _integer(
            era_current, "era_current", maximum=(1 << 64) - 1
        ),
        "era_period": normalized_profile["extrinsic_period"],
        "nonce": _integer(nonce, "nonce", maximum=(1 << 64) - 1),
        "block_hash": _raw_hash(block_hash, "block_hash"),
        "signature_payload_preimage_hash": sha256_bytes(preimage),
        "signed_message_hex": signed.hex(),
        "signed_message_hash": sha256_bytes(signed),
    }
    return {**body, "authorization_hash": sha256_json(body)}


def validate_weight_extrinsic_authorization_v2(
    value: Mapping[str, Any], *, profile: Mapping[str, Any]
) -> Dict[str, Any]:
    _require(isinstance(value, Mapping), "weight extrinsic authorization is invalid")
    expected_fields = {
        "schema_version",
        "validator_hotkey",
        "hotkey_public_key",
        "epoch_id",
        "netuid",
        "weight_receipt_hash",
        "weight_submission_event_hash",
        "weights_hash",
        "sparse_uids",
        "sparse_weights_u16",
        "chain_signing_profile_hash",
        "commitment_hex",
        "commitment_hash",
        "reveal_round",
        "call_data_hex",
        "call_data_hash",
        "era_current",
        "era_period",
        "nonce",
        "block_hash",
        "signature_payload_preimage_hash",
        "signed_message_hex",
        "signed_message_hash",
        "authorization_hash",
    }
    _require(set(value) == expected_fields, "weight extrinsic authorization fields are invalid")
    rebuilt = build_weight_extrinsic_authorization_v2(
        profile=profile,
        validator_hotkey=value["validator_hotkey"],
        hotkey_public_key_hex=value["hotkey_public_key"],
        epoch_id=value["epoch_id"],
        netuid=value["netuid"],
        weight_receipt_hash=value["weight_receipt_hash"],
        weight_submission_event_hash=value["weight_submission_event_hash"],
        weights_hash=value["weights_hash"],
        sparse_uids=value["sparse_uids"],
        sparse_weights_u16=value["sparse_weights_u16"],
        commitment=_hex_bytes(value["commitment_hex"], "commitment_hex"),
        reveal_round=value["reveal_round"],
        era_current=value["era_current"],
        nonce=value["nonce"],
        block_hash=value["block_hash"],
    )
    _require(dict(value) == rebuilt, "weight extrinsic authorization is not canonical")
    return rebuilt


def encode_serve_axon_call(
    *,
    profile: Mapping[str, Any],
    netuid: int,
    version: int,
    ip: int,
    port: int,
    ip_type: int,
    protocol: int,
    placeholder1: int,
    placeholder2: int,
) -> bytes:
    """Encode the exact Finney ``SubtensorModule.serve_axon`` call."""

    normalized = validate_chain_signing_profile(profile)
    normalized_ip_type = _integer(
        ip_type, "axon ip_type", minimum=4, maximum=6
    )
    _require(normalized_ip_type in (4, 6), "axon ip_type must be IPv4 or IPv6")
    return b"".join(
        (
            bytes.fromhex(normalized["serve_axon_call_index"]),
            _integer(netuid, "netuid", maximum=(1 << 16) - 1).to_bytes(
                2, "little"
            ),
            _integer(version, "axon version", maximum=(1 << 32) - 1).to_bytes(
                4, "little"
            ),
            _integer(ip, "axon ip", maximum=(1 << 128) - 1).to_bytes(
                16, "little"
            ),
            _integer(port, "axon port", minimum=1, maximum=(1 << 16) - 1).to_bytes(
                2, "little"
            ),
            normalized_ip_type.to_bytes(1, "little"),
            _integer(protocol, "axon protocol", maximum=(1 << 8) - 1).to_bytes(
                1, "little"
            ),
            _integer(placeholder1, "axon placeholder1", maximum=(1 << 8) - 1).to_bytes(
                1, "little"
            ),
            _integer(placeholder2, "axon placeholder2", maximum=(1 << 8) - 1).to_bytes(
                1, "little"
            ),
        )
    )


def build_serve_axon_extrinsic_authorization_v2(
    *,
    profile: Mapping[str, Any],
    validator_hotkey: str,
    hotkey_public_key_hex: str,
    netuid: int,
    version: int,
    ip: int,
    port: int,
    ip_type: int,
    protocol: int,
    placeholder1: int,
    placeholder2: int,
    era_current: int,
    nonce: int,
    block_hash: str,
) -> Dict[str, Any]:
    normalized_profile = validate_chain_signing_profile(profile)
    hotkey = str(validator_hotkey or "")
    _require(bool(_HOTKEY_RE.fullmatch(hotkey)), "validator_hotkey is invalid")
    hotkey_public_key = _hex_bytes(
        hotkey_public_key_hex, "hotkey_public_key", exact_bytes=32
    )
    normalized_ip_type = _integer(
        ip_type, "axon ip_type", minimum=4, maximum=6
    )
    _require(normalized_ip_type in (4, 6), "axon ip_type must be IPv4 or IPv6")
    call = encode_serve_axon_call(
        profile=normalized_profile,
        netuid=netuid,
        version=version,
        ip=ip,
        port=port,
        ip_type=ip_type,
        protocol=protocol,
        placeholder1=placeholder1,
        placeholder2=placeholder2,
    )
    preimage, signed = encode_weight_signature_payload(
        profile=normalized_profile,
        call_bytes=call,
        era_current=era_current,
        nonce=nonce,
        block_hash=block_hash,
    )
    body = {
        "schema_version": SERVE_AXON_EXTRINSIC_AUTHORIZATION_SCHEMA_VERSION,
        "validator_hotkey": hotkey,
        "hotkey_public_key": hotkey_public_key.hex(),
        "netuid": _integer(netuid, "netuid", maximum=(1 << 16) - 1),
        "version": _integer(version, "axon version", maximum=(1 << 32) - 1),
        "ip": _integer(ip, "axon ip", maximum=(1 << 128) - 1),
        "port": _integer(
            port, "axon port", minimum=1, maximum=(1 << 16) - 1
        ),
        "ip_type": normalized_ip_type,
        "protocol": _integer(
            protocol, "axon protocol", maximum=(1 << 8) - 1
        ),
        "placeholder1": _integer(
            placeholder1, "axon placeholder1", maximum=(1 << 8) - 1
        ),
        "placeholder2": _integer(
            placeholder2, "axon placeholder2", maximum=(1 << 8) - 1
        ),
        "chain_signing_profile_hash": sha256_json(normalized_profile),
        "call_data_hex": call.hex(),
        "call_data_hash": sha256_bytes(call),
        "era_current": _integer(
            era_current, "era_current", maximum=(1 << 64) - 1
        ),
        "era_period": normalized_profile["extrinsic_period"],
        "nonce": _integer(nonce, "nonce", maximum=(1 << 64) - 1),
        "block_hash": _raw_hash(block_hash, "block_hash"),
        "signature_payload_preimage_hash": sha256_bytes(preimage),
        "signed_message_hex": signed.hex(),
        "signed_message_hash": sha256_bytes(signed),
    }
    return {**body, "authorization_hash": sha256_json(body)}


def validate_serve_axon_extrinsic_authorization_v2(
    value: Mapping[str, Any], *, profile: Mapping[str, Any]
) -> Dict[str, Any]:
    _require(isinstance(value, Mapping), "serve axon authorization is invalid")
    expected_fields = {
        "schema_version",
        "validator_hotkey",
        "hotkey_public_key",
        "netuid",
        "version",
        "ip",
        "port",
        "ip_type",
        "protocol",
        "placeholder1",
        "placeholder2",
        "chain_signing_profile_hash",
        "call_data_hex",
        "call_data_hash",
        "era_current",
        "era_period",
        "nonce",
        "block_hash",
        "signature_payload_preimage_hash",
        "signed_message_hex",
        "signed_message_hash",
        "authorization_hash",
    }
    _require(set(value) == expected_fields, "serve axon authorization fields are invalid")
    rebuilt = build_serve_axon_extrinsic_authorization_v2(
        profile=profile,
        validator_hotkey=value["validator_hotkey"],
        hotkey_public_key_hex=value["hotkey_public_key"],
        netuid=value["netuid"],
        version=value["version"],
        ip=value["ip"],
        port=value["port"],
        ip_type=value["ip_type"],
        protocol=value["protocol"],
        placeholder1=value["placeholder1"],
        placeholder2=value["placeholder2"],
        era_current=value["era_current"],
        nonce=value["nonce"],
        block_hash=value["block_hash"],
    )
    _require(dict(value) == rebuilt, "serve axon authorization is not canonical")
    return rebuilt


def _application_message_text(message: bytes) -> str:
    payload = bytes(message)
    _require(0 < len(payload) <= 1024 * 1024, "application message size is invalid")
    try:
        return payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HotkeyAuthorityV2Error("application message must be UTF-8") from exc


def build_weight_inputs_request_v2(
    *,
    validator_hotkey: str,
    netuid: int,
    epoch_id: int,
    block: int,
    calculation_snapshot_hash: str,
    allocation_hash: str,
    leaderboard_window_start: str,
    leaderboard_window_end: str,
) -> Dict[str, Any]:
    hotkey = str(validator_hotkey or "")
    _require(bool(_HOTKEY_RE.fullmatch(hotkey)), "validator_hotkey is invalid")
    window_start, parsed_start = _timestamp(
        leaderboard_window_start, "leaderboard_window_start"
    )
    window_end, parsed_end = _timestamp(
        leaderboard_window_end, "leaderboard_window_end"
    )
    _require(parsed_end >= parsed_start, "leaderboard window is inverted")
    body = {
        "schema_version": WEIGHT_INPUT_REQUEST_SCHEMA_VERSION,
        "validator_hotkey": hotkey,
        "netuid": _integer(netuid, "netuid", maximum=(1 << 16) - 1),
        "epoch_id": _integer(epoch_id, "epoch_id", maximum=(1 << 64) - 1),
        "block": _integer(block, "block", maximum=(1 << 64) - 1),
        "calculation_snapshot_hash": _hash(
            calculation_snapshot_hash, "calculation_snapshot_hash"
        ),
        "allocation_hash": _hash(allocation_hash, "allocation_hash"),
        "leaderboard_window_start": window_start,
        "leaderboard_window_end": window_end,
    }
    return {**body, "request_hash": sha256_json(body)}


def validate_weight_inputs_request_v2(value: Mapping[str, Any]) -> Dict[str, Any]:
    _require(isinstance(value, Mapping), "weight input request is invalid")
    expected_fields = {
        "schema_version",
        "validator_hotkey",
        "netuid",
        "epoch_id",
        "block",
        "calculation_snapshot_hash",
        "allocation_hash",
        "leaderboard_window_start",
        "leaderboard_window_end",
        "request_hash",
    }
    _require(set(value) == expected_fields, "weight input request fields are invalid")
    rebuilt = build_weight_inputs_request_v2(
        validator_hotkey=value["validator_hotkey"],
        netuid=value["netuid"],
        epoch_id=value["epoch_id"],
        block=value["block"],
        calculation_snapshot_hash=value["calculation_snapshot_hash"],
        allocation_hash=value["allocation_hash"],
        leaderboard_window_start=value["leaderboard_window_start"],
        leaderboard_window_end=value["leaderboard_window_end"],
    )
    _require(dict(value) == rebuilt, "weight input request is not canonical")
    return rebuilt


def weight_inputs_request_message_v2(value: Mapping[str, Any]) -> str:
    return WEIGHT_INPUT_REQUEST_PREFIX + canonical_json(
        validate_weight_inputs_request_v2(value)
    )


def parse_weight_inputs_request_message_v2(message: bytes) -> Dict[str, Any]:
    text = _application_message_text(message)
    _require(
        text.startswith(WEIGHT_INPUT_REQUEST_PREFIX),
        "weight input request prefix is invalid",
    )
    try:
        value = json.loads(text[len(WEIGHT_INPUT_REQUEST_PREFIX) :])
    except (TypeError, ValueError) as exc:
        raise HotkeyAuthorityV2Error("weight input request JSON is invalid") from exc
    return validate_weight_inputs_request_v2(value)


def classify_application_message_v2(message: bytes, *, validator_hotkey: str) -> str:
    """Return the exact measured purpose for a recognized validator message."""

    hotkey = str(validator_hotkey or "")
    _require(bool(_HOTKEY_RE.fullmatch(hotkey)), "validator_hotkey is invalid")
    text = _application_message_text(message)

    if text.startswith(WEIGHT_INPUT_REQUEST_PREFIX):
        request = parse_weight_inputs_request_message_v2(message)
        _require(
            request["validator_hotkey"] == hotkey,
            "weight input request hotkey differs",
        )
        return "validator.gateway_weight_inputs.v2"

    if text.startswith("LEADPOET_VALIDATOR_BINDING|"):
        from leadpoet_canonical.binding import parse_binding_message

        parsed, parts, _error = parse_binding_message(text)
        _require(parsed and isinstance(parts, dict), "validator binding is invalid")
        _require(
            bool(re.fullmatch(r"[0-9a-f]{40}(?:[0-9a-f]{24})?", parts.get("version", ""))),
            "validator binding must use a full commit",
        )
        return "validator.gateway_binding.v2"

    exact_patterns = (
        (
            "validator.gateway_epoch_leads.v2",
            r"GET_EPOCH_LEADS:[0-9]+:%s" % re.escape(hotkey),
        ),
        (
            "validator.gateway_validation_batch.v2",
            r"VALIDATION_RESULT_BATCH:%s:[0-9a-f-]{36}:"
            r"[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}"
            r"(?:\.[0-9]{1,6})?\+00:00:[0-9a-f]{64}:[A-Za-z0-9_.:/-]{1,128}"
            % re.escape(hotkey),
        ),
        (
            "validator.fulfillment_scoring_fetch.v2",
            r"FULFILLMENT_SCORING:%s::[0-9a-f-]{36}:[0-9]+"
            % re.escape(hotkey),
        ),
        (
            "validator.fulfillment_score_submit.v2",
            r"FULFILLMENT_SCORE:%s:[A-Za-z0-9_.:-]{1,256}:[0-9a-f-]{36}:[0-9]+"
            % re.escape(hotkey),
        ),
    )
    for purpose, pattern in exact_patterns:
        if re.fullmatch(pattern, text):
            return purpose

    if re.fullmatch(r"[0-9]{9,20}", text):
        return "validator.qualification_registration.v2"

    # Existing cloud-curation messages are a five-minute bucket followed by
    # canonical JSON.  Only the two shapes used by the validator are allowed.
    if len(text) > 10 and text[:10].isdigit():
        try:
            document = json.loads(text[10:])
        except (TypeError, ValueError):
            document = None
        if isinstance(document, dict) and json.dumps(
            document, sort_keys=True, default=str
        ) == text[10:]:
            if document == {}:
                return "validator.curation_result_fetch.v2"
            if set(document) == {"num_leads", "business_desc", "target_uid"}:
                _require(
                    isinstance(document["num_leads"], int)
                    and not isinstance(document["num_leads"], bool)
                    and document["num_leads"] >= 0,
                    "curation num_leads is invalid",
                )
                _require(
                    isinstance(document["target_uid"], int)
                    and not isinstance(document["target_uid"], bool)
                    and 0 <= document["target_uid"] <= 65535,
                    "curation target_uid is invalid",
                )
                _require(
                    isinstance(document["business_desc"], str)
                    and len(document["business_desc"]) <= 100000,
                    "curation business description is invalid",
                )
                return "validator.curation_request.v2"

    # Bittensor dendrite request:
    # nonce.validator_hotkey.target_hotkey.uuid.body_hash
    dendrite = text.split(".")
    if len(dendrite) == 5 and dendrite[1] == hotkey:
        _require(dendrite[0].isdigit(), "dendrite nonce is invalid")
        _require(bool(_HOTKEY_RE.fullmatch(dendrite[2])), "dendrite target is invalid")
        _require(bool(_UUID_RE.fullmatch(dendrite[3])), "dendrite UUID is invalid")
        _require(bool(re.fullmatch(r"[0-9a-f]{64}", dendrite[4])), "dendrite body hash is invalid")
        return "validator.bittensor_dendrite.v2"

    # Bittensor axon response:
    # nonce.requester_hotkey.validator_hotkey.axon_uuid
    if len(dendrite) == 4 and dendrite[2] == hotkey:
        _require(dendrite[0].isdigit(), "axon nonce is invalid")
        _require(bool(_HOTKEY_RE.fullmatch(dendrite[1])), "axon requester is invalid")
        _require(bool(_UUID_RE.fullmatch(dendrite[3])), "axon UUID is invalid")
        return "validator.bittensor_axon.v2"

    raise HotkeyAuthorityV2Error("application message domain is not authorized")


def build_application_signature_request_v2(
    *, message: bytes, validator_hotkey: str, boot_identity_hash: str
) -> Dict[str, Any]:
    purpose = classify_application_message_v2(
        message, validator_hotkey=validator_hotkey
    )
    body = {
        "schema_version": APPLICATION_SIGNATURE_SCHEMA_VERSION,
        "purpose": purpose,
        "validator_hotkey": str(validator_hotkey),
        "boot_identity_hash": _hash(boot_identity_hash, "boot_identity_hash"),
        "message_hex": bytes(message).hex(),
        "message_hash": sha256_bytes(bytes(message)),
    }
    return {**body, "request_hash": sha256_json(body)}


def validate_application_signature_request_v2(
    value: Mapping[str, Any], *, validator_hotkey: str
) -> Dict[str, Any]:
    _require(
        isinstance(value, Mapping)
        and set(value)
        == {
            "schema_version",
            "purpose",
            "validator_hotkey",
            "boot_identity_hash",
            "message_hex",
            "message_hash",
            "request_hash",
        },
        "application signature request fields are invalid",
    )
    message = _hex_bytes(value["message_hex"], "message_hex")
    rebuilt = build_application_signature_request_v2(
        message=message,
        validator_hotkey=validator_hotkey,
        boot_identity_hash=value["boot_identity_hash"],
    )
    _require(dict(value) == rebuilt, "application signature request is not canonical")
    return rebuilt
