-- Inactive template. Render only after the bound rejudge is scored, drained, and the
-- corrected publication generated by the deployed service differs from the
-- archived decision. This aligns only the denormalized competition decision
-- before normal service publication. Signed reward, promotion, accepted weight,
-- score, source, and bank history remain unchanged.
BEGIN;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';

DO $corrected_publication336$
DECLARE
 active public.lab_arena_rounds;
 archived public.lab_arena_rounds;
 unsettled BIGINT;
 old_definition TEXT;
 corrected_outcome TEXT:='no_king';
 corrected_hotkey TEXT:=NULLIF('','');
 stable_before JSONB;
 stable_after JSONB;
BEGIN
 SELECT * INTO STRICT active FROM public.lab_arena_rounds
  WHERE round_id='arena-2026-09-20' FOR UPDATE;
 SELECT * INTO STRICT archived FROM public.lab_arena_rounds
  WHERE round_id='arena-2026-09-20-r339archive';
 SELECT pg_catalog.pg_get_functiondef(
  'public.lab_arena_rounds_write_once_v1()'::pg_catalog.regprocedure)
 INTO old_definition;

 IF EXISTS(SELECT 1 FROM pg_catalog.pg_trigger
   WHERE tgrelid='public.lab_arena_rounds'::pg_catalog.regclass
    AND NOT tgisinternal AND tgenabled<>'O') THEN
  RAISE EXCEPTION 'Sep20 corrected publication USER trigger state differs'
   USING ERRCODE='55000';
 END IF;

 SELECT pg_catalog.count(*) INTO unsettled
 FROM public.lab_arena_submissions s
 CROSS JOIN(VALUES('execute'::TEXT),('score'::TEXT)) k(kind)
 CROSS JOIN LATERAL(SELECT public.lab_arena__successful_call_cost_state(
  s.submission_id,k.kind,NULL) state)c
 WHERE s.round_id=active.round_id
  AND (COALESCE((c.state->>'inflight_calls')::BIGINT,-1)<>0
   OR COALESCE((c.state->>'success_unresolved_calls')::BIGINT,-1)<>0);

 stable_before:=pg_catalog.jsonb_build_object(
  'configuration_doc',active.configuration_doc,
  'rewards_enabled',active.rewards_enabled,'participants',active.participants,
  'benchmark_ref',active.benchmark_ref,'evaluation_date',active.evaluation_date,
  'icp_set_date',active.icp_set_date,
  'stage1_scoring_plan_doc',active.stage1_scoring_plan_doc,
  'stage2_scoring_plan_doc',active.stage2_scoring_plan_doc,
  'stage3_scoring_plan_doc',active.stage3_scoring_plan_doc,
  'finalists',active.finalists,
  'confirmation_bank_ref',active.confirmation_bank_ref,
  'confirmation_bank_hash',active.confirmation_bank_hash,
  'confirmation_cohort',active.confirmation_cohort,
  'champion_funding_frozen',active.champion_funding_frozen,
  'champion_submission_id',active.champion_submission_id,
  'champion_hotkey',active.champion_hotkey,
  'champion_fallback_providers',active.champion_fallback_providers,
  'effective_reward_epoch',active.effective_reward_epoch,
  'reward_basis_hash',active.reward_basis_hash,
  'reward_basis_doc',active.reward_basis_doc,
  'signing_key_doc',active.signing_key_doc,
  'reward_activated_at',active.reward_activated_at,
  'king_start_epoch',active.king_start_epoch,
  'promotion_required',active.promotion_required,
  'promotion_doc',active.promotion_doc,
  'baseline_promoted_at',active.baseline_promoted_at);

 IF active.status NOT IN('scored','published')
  OR archived.status IS DISTINCT FROM 'cancelled'
  OR archived.cancel_reason IS DISTINCT FROM
     'authorized_sep20_authority_preserving_rejudge_archive'
  OR pg_catalog.encode(extensions.digest(pg_catalog.to_jsonb(archived)::TEXT,
     'sha256'),'hex')<>'33945176e3b2b2067db67644f76dfa4f9aedddb269269f260a23ca5fab3c9666'
  OR pg_catalog.encode(extensions.digest(stable_before::TEXT,'sha256'),'hex')<>
     'f817331326fb8f319e50e776977dca41818ed8239c2aaaf4f31e2683cadb248b'
  OR pg_catalog.encode(extensions.digest(old_definition,'sha256'),'hex')<>
     'f6644ea2118e0af70c1b1c90c6eb0591507ee397edd31148102f5833cc99d74d'
  OR pg_catalog.encode(extensions.digest(COALESCE((SELECT pg_catalog.string_agg(
     pg_catalog.encode(extensions.digest(pg_catalog.to_jsonb(s)::TEXT,'sha256'),
     'hex'),'' ORDER BY submission_id) FROM public.lab_arena_submissions s
     WHERE s.round_id=active.round_id),''),'sha256'),'hex')<>
     '80147fc44b90f3e139820c27007a577c9d63f76eff5d4fcb02f1abc194e411a9'
  OR pg_catalog.encode(extensions.digest(COALESCE((SELECT pg_catalog.string_agg(
     pg_catalog.encode(extensions.digest(pg_catalog.to_jsonb(r)::TEXT,'sha256'),
     'hex'),'' ORDER BY run_id) FROM public.lab_arena_runs r
     WHERE r.round_id=active.round_id),''),'sha256'),'hex')<>'3d85e8197f7db2aacf5583721db1fe6dd4bc33d3160a1b5705632da3e20526e9'
  OR pg_catalog.encode(extensions.digest(COALESCE((SELECT pg_catalog.string_agg(
     pg_catalog.encode(extensions.digest(pg_catalog.to_jsonb(l)::TEXT,'sha256'),
     'hex'),'' ORDER BY entry_id) FROM public.lab_arena_ledger l
     WHERE l.round_id=active.round_id),''),'sha256'),'hex')<>'9871f26ed6327b3d762c2b6e0eb79de499dcae8dfd4260e980b300dc4e684d1a'
  OR unsettled<>0
  OR (SELECT pg_catalog.count(*) FROM public.lab_arena_runs
      WHERE round_id=active.round_id AND kind='score')<>98
  OR (SELECT pg_catalog.count(*) FROM public.lab_arena_runs
      WHERE round_id=active.round_id AND kind='score'
       AND status='accepted' AND terminal_cause='accepted')<>98
  OR (SELECT pg_catalog.count(DISTINCT assignment_id)
      FROM public.lab_arena_runs WHERE round_id=active.round_id AND kind='score'
       AND status='accepted' AND terminal_cause='accepted')<>98
  OR (SELECT pg_catalog.count(DISTINCT scored_run_id)
      FROM public.lab_arena_runs WHERE round_id=active.round_id AND kind='score'
       AND status='accepted' AND terminal_cause='accepted')<>98
  OR EXISTS(SELECT 1 FROM public.lab_arena_runs score_run
      WHERE score_run.round_id=active.round_id AND score_run.kind='score'
       AND (score_run.assignment_id NOT LIKE '%:score:rerun339'
        OR score_run.judgment_scope_doc->>'scorer_image_digest' IS DISTINCT FROM
           active.configuration_doc->>'scorer_image_digest'
        OR score_run.judgment_scope_doc->>'scorer_image_reference' IS DISTINCT FROM
           active.configuration_doc->>'scorer_image_reference'
        OR (score_run.status='accepted' AND
            (score_run.terminal_cause<>'accepted'
             OR score_run.scored_run_id IS NULL OR score_run.result_doc IS NULL))
        OR (score_run.status='failed' AND
            (score_run.terminal_cause NOT IN('judge_error','judge_timeout')
             OR NOT EXISTS(SELECT 1 FROM public.lab_arena_runs accepted_retry
                WHERE accepted_retry.round_id=score_run.round_id
                 AND accepted_retry.kind='score'
                 AND accepted_retry.assignment_id=score_run.assignment_id
                 AND accepted_retry.scored_run_id=score_run.scored_run_id
                 AND accepted_retry.attempt>score_run.attempt
                 AND accepted_retry.status='accepted'
                 AND accepted_retry.terminal_cause='accepted')))
        OR score_run.status NOT IN('accepted','failed')))
  OR EXISTS(SELECT 1 FROM public.lab_arena_runs
      WHERE round_id=active.round_id AND status IN('pending','leased','submitted'))
  OR corrected_outcome NOT IN('crowned','defended','retained_ineligible','no_king')
  OR (corrected_outcome='no_king' AND corrected_hotkey IS NOT NULL)
  OR (corrected_outcome<>'no_king' AND corrected_hotkey IS NULL)
  OR pg_catalog.encode(extensions.digest(
     '{"king_hotkey":"","king_submission_id":null,"outcome":"no_king","winner_submission_id":null}'::JSONB::TEXT,'sha256'),'hex')<>
     '82e0f3b50e3db5f2b396ce4a31546b74ac8feb5c4562c60e04163b8de77548c6'
  OR '{"king_hotkey":"","king_submission_id":null,"outcome":"no_king","winner_submission_id":null}'::JSONB->>'outcome'<>
     corrected_outcome
  OR NULLIF('{"king_hotkey":"","king_submission_id":null,"outcome":"no_king","winner_submission_id":null}'::JSONB->>'king_hotkey','')
     IS DISTINCT FROM corrected_hotkey
  OR archived.king_outcome IS DISTINCT FROM 'crowned'
  OR archived.king_hotkey IS DISTINCT FROM NULLIF('5FqcBT8JJ2Sr4KHWkpJG4nza9QtwGMSWXucQXeotVUEeM7VX','')
  OR (corrected_outcome IS NOT DISTINCT FROM archived.king_outcome
      AND corrected_hotkey IS NOT DISTINCT FROM archived.king_hotkey)
  OR (active.status='scored' AND (active.publication_doc IS NOT NULL
      OR active.published_at IS NOT NULL))
  OR (active.status='published' AND
      (pg_catalog.encode(extensions.digest(
        (active.publication_doc->'king_decision')::TEXT,'sha256'),'hex')<>
        '82e0f3b50e3db5f2b396ce4a31546b74ac8feb5c4562c60e04163b8de77548c6'
       OR active.king_outcome IS DISTINCT FROM corrected_outcome
       OR active.king_hotkey IS DISTINCT FROM corrected_hotkey))
  OR (active.status='scored' AND NOT (
      (active.king_outcome='crowned' AND
       active.king_hotkey IS NOT DISTINCT FROM NULLIF('5FqcBT8JJ2Sr4KHWkpJG4nza9QtwGMSWXucQXeotVUEeM7VX',''))
      OR (active.king_outcome IS NOT DISTINCT FROM corrected_outcome AND
       active.king_hotkey IS NOT DISTINCT FROM corrected_hotkey))) THEN
  RAISE EXCEPTION 'Sep20 corrected publication preimage differs'
   USING ERRCODE='55000';
 END IF;

 IF active.status='scored' AND
    (active.king_outcome IS DISTINCT FROM corrected_outcome OR
     active.king_hotkey IS DISTINCT FROM corrected_hotkey) THEN
  ALTER TABLE public.lab_arena_rounds DISABLE TRIGGER USER;
  UPDATE public.lab_arena_rounds SET
   king_outcome=corrected_outcome,king_hotkey=corrected_hotkey
   WHERE round_id=active.round_id;
  ALTER TABLE public.lab_arena_rounds ENABLE TRIGGER USER;
 END IF;

 SELECT pg_catalog.jsonb_build_object(
  'configuration_doc',current.configuration_doc,
  'rewards_enabled',current.rewards_enabled,'participants',current.participants,
  'benchmark_ref',current.benchmark_ref,'evaluation_date',current.evaluation_date,
  'icp_set_date',current.icp_set_date,
  'stage1_scoring_plan_doc',current.stage1_scoring_plan_doc,
  'stage2_scoring_plan_doc',current.stage2_scoring_plan_doc,
  'stage3_scoring_plan_doc',current.stage3_scoring_plan_doc,
  'finalists',current.finalists,
  'confirmation_bank_ref',current.confirmation_bank_ref,
  'confirmation_bank_hash',current.confirmation_bank_hash,
  'confirmation_cohort',current.confirmation_cohort,
  'champion_funding_frozen',current.champion_funding_frozen,
  'champion_submission_id',current.champion_submission_id,
  'champion_hotkey',current.champion_hotkey,
  'champion_fallback_providers',current.champion_fallback_providers,
  'effective_reward_epoch',current.effective_reward_epoch,
  'reward_basis_hash',current.reward_basis_hash,
  'reward_basis_doc',current.reward_basis_doc,
  'signing_key_doc',current.signing_key_doc,
  'reward_activated_at',current.reward_activated_at,
  'king_start_epoch',current.king_start_epoch,
  'promotion_required',current.promotion_required,
  'promotion_doc',current.promotion_doc,
  'baseline_promoted_at',current.baseline_promoted_at)
 INTO stable_after FROM public.lab_arena_rounds current
 WHERE current.round_id=active.round_id;
 IF stable_after IS DISTINCT FROM stable_before
  OR (SELECT king_outcome FROM public.lab_arena_rounds
      WHERE round_id=active.round_id) IS DISTINCT FROM corrected_outcome
  OR (SELECT king_hotkey FROM public.lab_arena_rounds
      WHERE round_id=active.round_id) IS DISTINCT FROM corrected_hotkey
  OR pg_catalog.pg_get_functiondef(
      'public.lab_arena_rounds_write_once_v1()'::pg_catalog.regprocedure)
      IS DISTINCT FROM old_definition
  OR EXISTS(SELECT 1 FROM pg_catalog.pg_trigger
      WHERE tgrelid='public.lab_arena_rounds'::pg_catalog.regclass
       AND NOT tgisinternal AND tgenabled<>'O') THEN
  RAISE EXCEPTION 'Sep20 corrected publication postimage differs'
   USING ERRCODE='55000';
 END IF;
END $corrected_publication336$;

DROP TRIGGER IF EXISTS lab_arena_000_sep20_rejudge332_publication_stop
 ON public.lab_arena_rounds;
DROP FUNCTION IF EXISTS public.lab_arena_sep20_rejudge332_publication_stop_v1();
COMMIT;
